# Generated by Django 5.1.7 on 2025-03-26 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aiagent",
            name="intelligenc_type_47b3ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="aiagentmodel",
            name="intelligenc_agent_i_841d56_idx",
        ),
        migrations.RemoveIndex(
            model_name="aichat",
            name="intelligenc_ai_agen_49ebe8_idx",
        ),
        migrations.RemoveIndex(
            model_name="aichat",
            name="intelligenc_created_fd961e_idx",
        ),
        migrations.RemoveIndex(
            model_name="aichatmessage",
            name="intelligenc_chat_id_fd14ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="aichatmessage",
            name="intelligenc_chat_id_bc1ec0_idx",
        ),
        migrations.RemoveIndex(
            model_name="aimodel",
            name="intelligenc_provide_a57071_idx",
        ),
        migrations.RemoveIndex(
            model_name="aitask",
            name="intelligenc_status_9fe547_idx",
        ),
        migrations.RemoveIndex(
            model_name="aitaskresource",
            name="intelligenc_task_id_5709f6_idx",
        ),
        migrations.RemoveIndex(
            model_name="aitaskresource",
            name="intelligenc_task_id_3559c5_idx",
        ),
        migrations.RemoveIndex(
            model_name="aitaskresource",
            name="intelligenc_task_id_9c7d4e_idx",
        ),
        migrations.RemoveIndex(
            model_name="aitool",
            name="intelligenc_type_178d49_idx",
        ),
        migrations.RemoveIndex(
            model_name="aiusagestat",
            name="intelligenc_user_id_19c917_idx",
        ),
        migrations.RemoveIndex(
            model_name="aiusagestat",
            name="intelligenc_ai_agen_fcf206_idx",
        ),
        migrations.RemoveIndex(
            model_name="aiusagestat",
            name="intelligenc_usage_t_32d5b3_idx",
        ),
        migrations.AddIndex(
            model_name="aiagent",
            index=models.Index(fields=["type"], name="intelligenc_type_f42471_idx"),
        ),
        migrations.AddIndex(
            model_name="aiagent",
            index=models.Index(fields=["status"], name="intelligenc_status_e204fa_idx"),
        ),
        migrations.AddIndex(
            model_name="aiagentmodel",
            index=models.Index(fields=["agent"], name="intelligenc_agent_i_b8dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="aiagentmodel",
            index=models.Index(
                fields=["is_primary"], name="intelligenc_is_prim_7bd5c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichat",
            index=models.Index(
                fields=["ai_agent"], name="intelligenc_ai_agen_d55a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichat",
            index=models.Index(fields=["status"], name="intelligenc_status_6b9ae4_idx"),
        ),
        migrations.AddIndex(
            model_name="aichat",
            index=models.Index(
                fields=["created_by"], name="intelligenc_created_fc8d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatmessage",
            index=models.Index(fields=["chat"], name="intelligenc_chat_id_d110ed_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatmessage",
            index=models.Index(
                fields=["message_order"], name="intelligenc_message_313e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatmessage",
            index=models.Index(fields=["role"], name="intelligenc_role_e01d3c_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["provider"], name="intelligenc_provide_b19f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(fields=["status"], name="intelligenc_status_2dce8d_idx"),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["priority"], name="intelligenc_priorit_bdd89d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitaskresource",
            index=models.Index(fields=["task"], name="intelligenc_task_id_4f47db_idx"),
        ),
        migrations.AddIndex(
            model_name="aitaskresource",
            index=models.Index(
                fields=["resource_type"], name="intelligenc_resourc_e180da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitaskresource",
            index=models.Index(
                fields=["processing_status"], name="intelligenc_process_224e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitool",
            index=models.Index(fields=["type"], name="intelligenc_type_73d4df_idx"),
        ),
        migrations.AddIndex(
            model_name="aitool",
            index=models.Index(fields=["status"], name="intelligenc_status_0fe4fd_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(fields=["user"], name="intelligenc_user_id_8fa1eb_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(
                fields=["created_at"], name="intelligenc_created_99a851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(
                fields=["ai_agent"], name="intelligenc_ai_agen_64866f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(
                fields=["ai_model"], name="intelligenc_ai_mode_8a7805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(
                fields=["usage_type"], name="intelligenc_usage_t_fb3bbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagestat",
            index=models.Index(
                fields=["success"], name="intelligenc_success_9f1677_idx"
            ),
        ),
    ]
