# Generated by Django 5.1.7 on 2025-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("pending", "En attente"),
                    ("sent", "Envoyé"),
                    ("failed", "Échec"),
                    ("archived", "Archivé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
