CREATE TABLE `ai_agents` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT,
    `type` ENUM('GENERAL', 'SPECIALIZED', 'CUSTOM') NOT NULL,
    `configuration` JSON,
    `system_prompt` TEXT,
    `capabilities` JSON,
    `status` ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE') DEFAULT 'ACTIVE',
    `version` INT NOT NULL DEFAULT 1,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_agent_name` (`name`),
    INDEX `idx_ai_agent_type_status` (`type`, `status`),
    INDEX `idx_ai_agent_created` (`created_by`),
    INDEX `idx_ai_agent_updated` (`updated_by`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_models` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `provider` VARCHAR(100) NOT NULL,
    `model_version` VARCHAR(50) NOT NULL,
    `capabilities` JSON,
    `parameters` JSON,
    `token_limit` INT NOT NULL,
    `cost_per_1k_tokens` DECIMAL(10,6),
    `status` ENUM('ACTIVE', 'INACTIVE', 'DEPRECATED') DEFAULT 'ACTIVE',
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_model_name_version` (`name`, `model_version`),
    INDEX `idx_ai_model_provider_status` (`provider`, `status`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_models` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `agent_id` BIGINT NOT NULL,
    `model_id` BIGINT NOT NULL,
    `is_primary` BOOLEAN NOT NULL DEFAULT FALSE,
    `configuration` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_model` (`agent_id`, `model_id`),
    INDEX `idx_agent_model_primary` (`agent_id`, `is_primary`),
    FOREIGN KEY (`agent_id`) REFERENCES `ai_agents`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`model_id`) REFERENCES `ai_models`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_prompts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(150) NOT NULL,
    `content` TEXT NOT NULL,
    `description` TEXT,
    `category` VARCHAR(100),
    `tags` JSON,
    `is_template` BOOLEAN DEFAULT FALSE,
    `is_public` BOOLEAN DEFAULT FALSE,
    `version` INT NOT NULL DEFAULT 1,
    `ai_agent_id` BIGINT,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_prompt_search` (`title`(50), `category`, `is_template`, `is_public`),
    INDEX `idx_prompt_agent` (`ai_agent_id`),
    INDEX `idx_prompt_created` (`created_by`),
    INDEX `idx_prompt_updated` (`updated_by`),
    INDEX `idx_prompt_deleted` (`deleted_at`),
    FOREIGN KEY (`ai_agent_id`) REFERENCES `ai_agents`(`id`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_prompt_versions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `prompt_id` BIGINT NOT NULL,
    `version_number` INT NOT NULL,
    `content` TEXT NOT NULL,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `comment` TEXT,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_prompt_version` (`prompt_id`, `version_number`),
    INDEX `idx_prompt_version_created` (`created_by`),
    FOREIGN KEY (`prompt_id`) REFERENCES `ai_prompts`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_chats` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(150) NOT NULL,
    `description` TEXT,
    `ai_agent_id` BIGINT NOT NULL,
    `settings` JSON,
    `status` ENUM('ACTIVE', 'ARCHIVED', 'DELETED') DEFAULT 'ACTIVE',
    `last_message_at` TIMESTAMP NULL,
    `folder_id` BIGINT,
    `document_id` BIGINT,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_chat_search` (`ai_agent_id`, `status`, `created_by`),
    INDEX `idx_chat_recent` (`created_by`, `last_message_at`),
    INDEX `idx_chat_folder` (`folder_id`),
    INDEX `idx_chat_document` (`document_id`),
    FOREIGN KEY (`ai_agent_id`) REFERENCES `ai_agents`(`id`),
    FOREIGN KEY (`folder_id`) REFERENCES `folders`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_chat_messages` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `chat_id` BIGINT NOT NULL,
    `content` TEXT NOT NULL,
    `role` ENUM('USER', 'ASSISTANT', 'SYSTEM') NOT NULL,
    `message_order` INT NOT NULL,
    `tokens_input` INT DEFAULT 0,
    `tokens_output` INT DEFAULT 0,
    `model_id` BIGINT,
    `metadata` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_message_lookup` (`chat_id`, `message_order`),
    INDEX `idx_message_role` (`chat_id`, `role`),
    INDEX `idx_message_model` (`model_id`),
    FOREIGN KEY (`chat_id`) REFERENCES `ai_chats`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`model_id`) REFERENCES `ai_models`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_chat_attachments` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `message_id` BIGINT NOT NULL,
    `file_path` VARCHAR(255) NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_type` VARCHAR(100) NOT NULL,
    `file_size` BIGINT NOT NULL,
    `document_id` BIGINT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_attachment_message` (`message_id`),
    INDEX `idx_attachment_type` (`file_type`),
    INDEX `idx_attachment_document` (`document_id`),
    FOREIGN KEY (`message_id`) REFERENCES `ai_chat_messages`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_tools` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT,
    `type` ENUM('EMAIL_PROCESSOR', 'FILE_ANALYZER', 'PROJECT_MANAGER', 'CODE_GENERATOR', 'DATA_EXTRACTOR', 'CUSTOM') NOT NULL,
    `capabilities` JSON,
    `configuration` JSON,
    `api_endpoint` VARCHAR(255),
    `version` VARCHAR(50) NOT NULL,
    `status` ENUM('ACTIVE', 'INACTIVE', 'DEPRECATED') DEFAULT 'ACTIVE',
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_tool_name_version` (`name`, `version`),
    INDEX `idx_ai_tool_search` (`type`, `status`),
    INDEX `idx_ai_tool_created` (`created_by`),
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_tools` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `agent_id` BIGINT NOT NULL,
    `tool_id` BIGINT NOT NULL,
    `configuration` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_tool` (`agent_id`, `tool_id`),
    FOREIGN KEY (`agent_id`) REFERENCES `ai_agents`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`tool_id`) REFERENCES `ai_tools`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_tasks` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(150) NOT NULL,
    `description` TEXT NOT NULL,
    `ai_agent_id` BIGINT NOT NULL,
    `ai_tool_id` BIGINT,
    `model_id` BIGINT,
    `task_type` ENUM('ANALYSIS', 'CLASSIFICATION', 'SUMMARIZATION', 'TRANSFORMATION', 'EXTRACTION', 'RESPONSE', 'ENTITY_RECOGNITION', 'SENTIMENT', 'CUSTOM') NOT NULL,
    `priority` ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') DEFAULT 'MEDIUM',
    `status` ENUM('PENDING', 'QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED') DEFAULT 'PENDING',
    `parameters` JSON,
    `progress` TINYINT DEFAULT 0,
    `result_summary` TEXT,
    `result_json` JSON,
    `tokens_input` INT DEFAULT 0,
    `tokens_output` INT DEFAULT 0,
    `primary_document_id` BIGINT,
    `primary_folder_id` BIGINT,
    `scheduled_at` TIMESTAMP NULL,
    `started_at` TIMESTAMP NULL,
    `completed_at` TIMESTAMP NULL,
    `duration_seconds` INT,
    `error_message` TEXT,
    `parent_task_id` BIGINT,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_by` BIGINT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_task_agent_tool` (`ai_agent_id`, `ai_tool_id`),
    INDEX `idx_task_model` (`model_id`),
    INDEX `idx_task_status_priority` (`status`, `priority`),
    INDEX `idx_task_schedule` (`status`, `scheduled_at`),
    INDEX `idx_task_type` (`task_type`),
    INDEX `idx_task_document` (`primary_document_id`),
    INDEX `idx_task_folder` (`primary_folder_id`),
    INDEX `idx_task_created_user` (`created_by`, `created_at`),
    INDEX `idx_task_parent` (`parent_task_id`),
    FOREIGN KEY (`ai_agent_id`) REFERENCES `ai_agents`(`id`),
    FOREIGN KEY (`ai_tool_id`) REFERENCES `ai_tools`(`id`),
    FOREIGN KEY (`model_id`) REFERENCES `ai_models`(`id`),
    FOREIGN KEY (`primary_document_id`) REFERENCES `documents`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`primary_folder_id`) REFERENCES `folders`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`parent_task_id`) REFERENCES `ai_tasks`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`),
    FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_task_resources` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT NOT NULL,
    `resource_type` ENUM('EMAIL', 'FILE', 'FOLDER', 'PROJECT', 'WORKSPACE', 'DATABASE', 'API', 'DOCUMENT', 'CODE', 'OTHER') NOT NULL,
    `resource_id` BIGINT,
    `resource_path` VARCHAR(255),
    `resource_name` VARCHAR(255) NOT NULL,
    `resource_metadata` JSON,
    `is_input` BOOLEAN NOT NULL DEFAULT TRUE,
    `is_output` BOOLEAN NOT NULL DEFAULT FALSE,
    `processing_status` ENUM('PENDING', 'PROCESSED', 'FAILED', 'SKIPPED') DEFAULT 'PENDING',
    `processing_result` TEXT,
    `document_id` BIGINT,
    `folder_id` BIGINT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_task_resource_lookup` (`task_id`, `resource_type`),
    INDEX `idx_task_resource_io` (`task_id`, `is_input`, `is_output`),
    INDEX `idx_task_resource_status` (`task_id`, `processing_status`),
    INDEX `idx_task_resource_document` (`document_id`),
    INDEX `idx_task_resource_folder` (`folder_id`),
    FOREIGN KEY (`task_id`) REFERENCES `ai_tasks`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`folder_id`) REFERENCES `folders`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_task_logs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT NOT NULL,
    `log_level` ENUM('INFO', 'WARNING', 'ERROR', 'DEBUG') NOT NULL DEFAULT 'INFO',
    `message` TEXT NOT NULL,
    `details` JSON,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_task_log_lookup` (`task_id`, `log_level`, `created_at`),
    FOREIGN KEY (`task_id`) REFERENCES `ai_tasks`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_usage_stats` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `ai_agent_id` BIGINT,
    `ai_model_id` BIGINT,
    `ai_tool_id` BIGINT,
    `usage_type` ENUM('CHAT', 'TASK', 'PROMPT', 'TOOL_CALL') NOT NULL,
    `task_id` BIGINT,
    `resource_id` BIGINT,
    `document_id` BIGINT,
    `folder_id` BIGINT,
    `tokens_input` INT DEFAULT 0,
    `tokens_output` INT DEFAULT 0,
    `duration_ms` INT DEFAULT 0,
    `cost` DECIMAL(10,6) DEFAULT 0,
    `success` BOOLEAN DEFAULT TRUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_usage_user_time` (`user_id`, `created_at`),
    INDEX `idx_usage_agent_model` (`ai_agent_id`, `ai_model_id`),
    INDEX `idx_usage_task` (`task_id`),
    INDEX `idx_usage_type_success` (`usage_type`, `success`),
    INDEX `idx_usage_document` (`document_id`),
    INDEX `idx_usage_folder` (`folder_id`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
    FOREIGN KEY (`ai_agent_id`) REFERENCES `ai_agents`(`id`),
    FOREIGN KEY (`ai_model_id`) REFERENCES `ai_models`(`id`),
    FOREIGN KEY (`ai_tool_id`) REFERENCES `ai_tools`(`id`),
    FOREIGN KEY (`task_id`) REFERENCES `ai_tasks`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`folder_id`) REFERENCES `folders`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_reference_data` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `reference_list_id` BIGINT NOT NULL,
    `ai_agent_id` BIGINT NOT NULL,
    `usage` ENUM('TRAINING', 'REFERENCE', 'FINE_TUNING', 'CONTEXT') NOT NULL,
    `created_by` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_reference_list` (`reference_list_id`, `ai_agent_id`, `usage`),
    INDEX `idx_ai_reference_agent` (`ai_agent_id`),
    FOREIGN KEY (`reference_list_id`) REFERENCES `reference_lists`(`id`),
    FOREIGN KEY (`ai_agent_id`) REFERENCES `ai_agents`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


