# Generated by Django 5.1.7 on 2025-03-26 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0001_initial"),
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="correspondence.correspondenceaction",
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("duplicate", "Duplicate"),
                    ("copy", "Copy"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="priority",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="correspondence.correspondencepriority",
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="recipient_organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_correspondences",
                to="tools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="recipient_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_correspondences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="typology",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="correspondence.correspondencetypology",
            ),
        ),
        migrations.CreateModel(
            name="CorrespondenceFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="correspondence",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondences",
                to="correspondence.correspondencefolder",
            ),
        ),
    ]
