# Generated by Django 5.1.7 on 2025-03-26 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0002_correspondence_is_favorite_and_more"),
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="recipient_organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_correspondences",
                to="tools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="recipient_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_correspondences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
