# Generated by Django 5.1.7 on 2025-03-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
