# Generated by Django 5.1.7 on 2025-03-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=191, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_workspace_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="workspace.workspacefolder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workspace_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="workspace.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("description", models.TextField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=191, null=True)),
                ("file_size", models.BigIntegerField(null=True)),
                ("file_type", models.CharField(max_length=50, null=True)),
                ("mime_type", models.CharField(max_length=100, null=True)),
                ("version", models.IntegerField(default=1)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_workspace_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_workspace_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workspace_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="workspace.workspacefolder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="root_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="root_workspace",
                to="workspace.workspacefolder",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="workspace.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceDocumentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_document_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="workspace.workspacedocument",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_document_permissions",
                        to="auth.group",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workspace_document_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_document_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document"], name="workspace_w_documen_19c266_idx"
                    ),
                    models.Index(
                        fields=["user"], name="workspace_w_user_id_5e891b_idx"
                    ),
                    models.Index(
                        fields=["group"], name="workspace_w_group_i_73d8dd_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="workspace_w_created_50c9af_idx"
                    ),
                    models.Index(
                        fields=["updated_by"], name="workspace_w_updated_8d9544_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceDocumentShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_token", models.CharField(max_length=191, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("max_access_count", models.IntegerField(blank=True, null=True)),
                ("permission_type", models.CharField(default="read", max_length=20)),
                ("password_protected", models.BooleanField(default=False)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_document_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="workspace.workspacedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document"], name="workspace_w_documen_21adaa_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="workspace_w_expires_34c7d0_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="workspace_w_created_e4e9f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("file_path", models.CharField(max_length=191, null=True)),
                ("file_size", models.BigIntegerField(null=True)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspace_document_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="workspace.workspacedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document"], name="workspace_w_documen_df3586_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="workspace_w_created_cb3bc4_idx"
                    ),
                ],
                "unique_together": {("document", "version")},
            },
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(
                fields=["workspace"], name="workspace_w_workspa_f3b448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(
                fields=["parent_folder"], name="workspace_w_parent__b59671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(fields=["path"], name="workspace_w_path_4d985c_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(
                fields=["created_by"], name="workspace_w_created_3a95bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(
                fields=["updated_by"], name="workspace_w_updated_cb4fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacefolder",
            index=models.Index(
                fields=["deleted_by"], name="workspace_w_deleted_3581b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["folder"], name="workspace_w_folder__f2e8d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(fields=["name"], name="workspace_w_name_8000d9_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["file_type"], name="workspace_w_file_ty_513930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["is_locked"], name="workspace_w_is_lock_4847f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["locked_by"], name="workspace_w_locked__04cd0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["created_by"], name="workspace_w_created_12f325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["updated_by"], name="workspace_w_updated_c7b262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedocument",
            index=models.Index(
                fields=["deleted_by"], name="workspace_w_deleted_687208_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["owner"], name="workspace_w_owner_i_469320_idx"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["created_by"], name="workspace_w_created_295d4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["updated_by"], name="workspace_w_updated_bd6e6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["deleted_by"], name="workspace_w_deleted_0df486_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["created_by"], name="workspace_w_created_7500ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["updated_by"], name="workspace_w_updated_70ce7a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together={("workspace", "user")},
        ),
    ]
