# Generated by Django 5.1.7 on 2025-03-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("share", "Shared"),
                            ("unshare", "Unshared"),
                            ("lock", "Locked"),
                            ("unlock", "Unlocked"),
                            ("upload", "Uploaded"),
                            ("download", "Downloaded"),
                            ("comment", "Commented"),
                            ("move", "Moved"),
                            ("copy", "Copied"),
                            ("rename", "Renamed"),
                            ("restore", "Restored"),
                            ("archive", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.IntegerField()),
                ("target_name", models.CharField(max_length=191)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["workspace"], name="workspace_a_workspa_f66f9a_idx"
                    ),
                    models.Index(
                        fields=["user"], name="workspace_a_user_id_2f3f81_idx"
                    ),
                    models.Index(
                        fields=["action"], name="workspace_a_action_378e5d_idx"
                    ),
                    models.Index(
                        fields=["target_type"], name="workspace_a_target__9e3258_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="workspace_a_timesta_f60872_idx"
                    ),
                ],
            },
        ),
    ]
